spring:
  application:
    name: SocialNetwork
  data:
    mongodb:
      uri: mongodb+srv://toantoanpham1910:Songtoan1910@social-network.awto8.mongodb.net/social-network

server:
  port: 8080

security:
  jwt:
    secret: Y2JkN2M4NjU3NTM4Y2ZiNDEyMjU5NjM1ZGVhMDIwOGFiMzZiYjY0MTJmMDVlZTY3ZTQyMzZjMTA4YWIxODk3YzI4MTkxNTkzZjFmYmQ5ZGM5MTA1NmVmZjAyODExZTQxMGRlMWI1M2U5MDEzNDY1ZDJhMmZiODhmMDI0MWYyNWQ=
    # Token is valid 24 hours
    token-validity-in-seconds: 86400